### ISSUE TITLE
Add off-canvas menu

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-ui#11]
```HTML
<nav class="sidebar-offcanvas">
  …
</nav>
  
<main class="content-offcanvas">
  <button class="close">×</button>

  …
</main>
```

```SCSS
.-open-offcanvas {
  .sidebar-offcanvas { transform: translateX(-100%); }
  .content-offcanvas { 
    left: 0;
    overflow-x: hidden;
  }
}

.sidebar-offcanvas {
  width: 15rem;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  overflow-y: auto;
  transition: transform $transition-duration;
}

.content-offcanvas {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 15rem;
  overflow-y: auto;
  transition: left $transition-duration;

  & > .close {
    position: absolute;
    top: 0;
    left: 0;
  }
}
```

And the user would apply something like the following with JS

```JS
$('.content-offcanvas .close').click(function(){
  $('body').toggleClass('-open-offcanvas');
});
```
